

clean_sub_lp:
	rm -f files/proofs/*/lemmas/*.lp

clean_sub_p:
	rm -f files/proofs/*/lemmas/*.p

clean_all:
	rm -rf files/traces
	rm -rf files/proofs

clean_tptp:
	rm -rf files/problems

clean_full: clean_all clean_tptp
	rm -f generation_data.txt